---
name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - 'head'
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Update bundler
        env:
          RUBY_VERSION: ${{ matrix.ruby }}
        run: |
          case ${RUBY_VERSION} in
            truffleruby|truffleruby-head)
              gem install bundler -v 2.5.18
            ;;

            *)
              gem update --system
            ;;
          esac

          bundle install

      - name: Run tests
        run: bin/rspec
